# Gradle Properties
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

# Minecraft/NeoForge Properties
minecraft_version=1.21.10
neoforge_version=21.10.64

# Mod Properties
mod_id=boostedbrightness
mod_version=1.0.0
maven_group=net.boostedbrightness
archives_base_name=boosted-brightness