org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
neo_version=26.1.0.1-beta
neo_version_range=[26.1,)
loader_version_range=[1,)

mod_id=boostedbrightness
mod_name=Boosted Brightness Remastered
mod_license=All Rights Reserved
mod_version=1.0
mod_group_id=net.boostedbrightness
mod_authors=Sarocesch
mod_description=Boosted Brightness Remastered
