modLoader="javafml"
loaderVersion="[5,)"
license="MIT"
issueTrackerURL="https://github.com/adamviola/BoostedBrightness/issues"

[[mods]]
modId="boostedbrightness"
version="${file.jarVersion}"
displayName="Boosted Brightness"
description='''
Allows you to set your brightness beyond default levels.
Includes keybindings for quick brightness switching and a config screen.
'''
logoFile="assets/boostedbrightness/icon.png"
authors="adamviola, sarocesch"
displayURL="https://github.com/adamviola/BoostedBrightness"

[[dependencies.boostedbrightness]]
modId="neoforge"
type="required"
versionRange="[21.10,)"
ordering="NONE"
side="CLIENT"

[[dependencies.boostedbrightness]]
modId="minecraft"
type="required"
versionRange="[1.21.10,1.22)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config="boostedbrightness.mixins.json"
